Repository googleinterns/step188-2020, pull requests merged in 2020-07, with the labels that each got.

#2 Add linters.
  .eslintrc.yml
  .github/workflows/csslint.yaml
  .github/workflows/eslint.yaml
  .github/workflows/javabuild.yaml
  .github/workflows/javalint.yaml
  .github/workflows/markdownlint.yaml
  .htmllintrc
  .stylelintrc.json
  package.json
Labels: Setup

#15 Add Event Creation UI form
  project/src/main/webapp/create-event.css
  project/src/main/webapp/create-event.html
Labels: UI

#13 Add UI skeleton with User page
  project/src/main/webapp/header.html
  project/src/main/webapp/index.html
  project/src/main/webapp/profile.css
  project/src/main/webapp/profile.html
  project/src/main/webapp/script.js
  project/src/main/webapp/style.css
Labels: UI

#31 [1/X] Styling header and home page
  project/src/main/webapp/header.css
  project/src/main/webapp/header.html
  project/src/main/webapp/index.css
  project/src/main/webapp/index.html
Labels: UI

#11 Add User class
  project/pom.xml
  project/src/main/java/com/google/sps/data/User.java
  project/src/test/java/com/google/sps/UserTest.java
Labels: API

#35 [2/Y] Style Event Discovery Page
  project/src/main/webapp/events-feed.css
  project/src/main/webapp/events-feed.html
Labels: UI

#37 [3/Y] Styling Profile Page + minor UI fixes
  project/src/main/webapp/create-event.css
  project/src/main/webapp/create-event.html
  project/src/main/webapp/index.html
  project/src/main/webapp/profile.css
  project/src/main/webapp/profile.html
Labels: UI

#34 Add Cloud Spanner tests
  project/pom.xml
  project/src/main/java/com/google/sps/data/Table.java
  project/src/main/java/com/google/sps/data/User.java
  project/src/main/java/com/google/sps/utilities/DatabaseWrapper.java
Labels: DB

#41 Make ID field names consistent
  project/src/main/java/com/google/sps/data/Event.java
  project/src/main/java/com/google/sps/data/User.java
  project/src/main/java/com/google/sps/utilities/DatabaseWrapper.java
Labels: enhancement
