Repository googleinterns/step188-2020, pull requests merged in 2020-08, with the labels that each got.

#54 Add Common utility functions
  project/pom.xml
  project/src/main/java/com/google/sps/utilities/CommonUtils.java
  project/src/test/java/com/google/sps/CommonUtilsTest.java
Labels: API

#69 Fix input tag styling
  project/src/main/webapp/create-event.html
  project/src/main/webapp/event-details.html
  project/src/main/webapp/events-feed.css
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/profile-edit.html
  project/src/main/webapp/profile.css
  project/src/main/webapp/profile.html
  project/src/main/webapp/styles.css
Labels: UI

#67 Restructure linking for logged-in/-out users
  project/pom.xml
  project/src/main/webapp/create-event.html
  project/src/main/webapp/create-volunteering-opportunity.html
  project/src/main/webapp/event-details.html
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/header.html
  project/src/main/webapp/index.html
  project/src/main/webapp/index.js
  project/src/main/webapp/profile-edit.html
  project/src/main/webapp/profile.html
  project/src/main/webapp/script.js
  project/src/main/webapp/shared.js
  project/src/main/webapp/signup.html
Labels: UI

#86 Add preset option for interests and skills (BACKEND)
  project/src/main/java/com/google/sps/servlets/PrefilledInformationServlet.java
  project/src/main/java/com/google/sps/utilities/PrefilledInformationConstants.java
  project/src/test/java/com/google/sps/PrefilledInformationTest.java
Labels: API

#83 Add preset option for interests and skills (FRONTEND)
  project/src/main/webapp/create-event.css
  project/src/main/webapp/create-event.html
  project/src/main/webapp/create-event.js
  project/src/main/webapp/create-volunteering-opportunity.html
  project/src/main/webapp/event-details.html
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/header.html
  project/src/main/webapp/index.html
  project/src/main/webapp/profile-edit.css
  project/src/main/webapp/script.js
  project/src/main/webapp/shared.js
  project/src/main/webapp/signup.html
  project/src/main/webapp/styles.css
Labels: UI

#87 [Ready for Review] Dynamic event cards (BACKEND)
  .gitignore
  project/src/main/java/com/google/sps/servlets/EventCreationServlet.java
  project/src/main/java/com/google/sps/servlets/EventDetailServlet.java
  project/src/main/java/com/google/sps/servlets/UserProfileUpdateServlet.java
  project/src/main/java/com/google/sps/utilities/SpannerTasks.java
  project/src/main/java/com/google/sps/utilities/SpannerTestTasks.java
  project/src/test/java/com/google/sps/EventDetailTest.java
Labels: API, DB

#105 User Profile: dynamic events (FRONTEND)
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/events-feed.js
  project/src/main/webapp/profile.js
  project/src/main/webapp/shared.js
Labels: API, UI

#114 Fix frontend user profile tag edits
  project/src/main/webapp/create-event.js
  project/src/main/webapp/profile-edit.html
  project/src/main/webapp/profile-edit.js
  project/src/main/webapp/profile.html
  project/src/main/webapp/profile.js
  project/src/main/webapp/shared.js
Labels: LIB, UI

#119 [Ready for review] Add volopp tags for frontend
  project/src/main/webapp/create-volunteering-opportunity.html
  project/src/main/webapp/create-volunteering-opportunity.js
Labels: LIB, UI

#123 Add functionality to retrieve events a user is hosting
  project/src/main/java/com/google/sps/servlets/UserProfileEventsServlet.java
  project/src/main/java/com/google/sps/utilities/SpannerTasks.java
  project/src/test/java/com/google/sps/UserProfileEventsTest.java
Labels: API, DB

#132 Fix user profile UI fields
  project/src/main/java/com/google/sps/utilities/SpannerTestTasks.java
  project/src/main/java/com/google/sps/utilities/TestUtils.java
  project/src/main/webapp/create-event.css
  project/src/main/webapp/create-event.html
  project/src/main/webapp/event-card.html
  project/src/main/webapp/profile.html
  project/src/main/webapp/profile.js
  project/src/main/webapp/shared.js
  project/src/main/webapp/styles.css
Labels: UI

#133 Add user to DB as soon as registration finishes
  project/src/main/java/com/google/sps/servlets/UserProfileUpdateServlet.java
Labels: API, bug

#135 Add Blobstore functionality (FRONTEND)
  project/src/main/webapp/assets/default_profile.jpg
  project/src/main/webapp/profile-edit.css
  project/src/main/webapp/profile-edit.html
  project/src/main/webapp/profile-edit.js
  project/src/main/webapp/profile.css
  project/src/main/webapp/profile.html
  project/src/main/webapp/profile.js
  project/src/main/webapp/shared.js
Labels: API, LIB, UI, enhancement

#144 Fix some test-failing code because of merge
  project/src/main/java/com/google/sps/servlets/EventRegistrationServlet.java
  project/src/main/java/com/google/sps/servlets/UserProfileUpdateServlet.java
  project/src/test/java/com/google/sps/EventDetailTest.java
Labels: bug

#148 Fix tag bug
  project/src/main/webapp/profile-edit.js
Labels: LIB, UI, bug

#137 Add interest filters to discovery page
  project/src/main/java/com/google/sps/servlets/EventCreationServlet.java
  project/src/main/java/com/google/sps/utilities/CommonUtils.java
  project/src/main/java/com/google/sps/utilities/PrefilledInformationConstants.java
  project/src/main/webapp/create-event.html
  project/src/main/webapp/event-details.html
  project/src/main/webapp/events-feed.css
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/events-feed.js
  project/src/test/java/com/google/sps/EventSpannerTasksTest.java
Labels: API

#145 [1/X] Event ranking (BACKEND)
  .gitignore
  project/src/main/java/com/google/sps/utilities/EventRanker.java
  project/src/test/java/com/google/sps/EventRankerTest.java
Labels: API

#151 [1/Z] Event ranking
  project/src/main/java/com/google/sps/data/Event.java
  project/src/main/java/com/google/sps/servlets/UserProfileUpdateServlet.java
  project/src/main/java/com/google/sps/servlets/VolunteeringFormHandlerServlet.java
  project/src/main/java/com/google/sps/utilities/SpannerTasks.java
  project/src/main/java/com/google/sps/utilities/SpannerTestTasks.java
  project/src/main/webapp/event-card.html
  project/src/main/webapp/events-feed.css
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/shared.js
  project/src/main/webapp/styles.css
  project/src/test/java/com/google/sps/EventDetailTest.java
Labels: LIB, UI

#147 [2/X] Event ranking (BACKEND)
  project/src/main/java/com/google/sps/servlets/EventRankerServlet.java
  project/src/main/java/com/google/sps/utilities/EventRanker.java
  project/src/test/java/com/google/sps/EventRankerServletTest.java
  project/src/test/java/com/google/sps/EventRankerTest.java
Labels: API, DB

#179 Configure edit and register buttons for hosts and non-hosts
  project/src/main/java/com/google/sps/servlets/EventRegistrationServlet.java
  project/src/main/webapp/event-card.html
  project/src/main/webapp/event-details.css
  project/src/main/webapp/event-details.html
  project/src/main/webapp/event-details.js
  project/src/main/webapp/events-feed.js
  project/src/main/webapp/shared.js
  project/src/main/webapp/styles.css
Labels: UI, bug

#191 Fix event details bug
  project/src/main/java/com/google/sps/servlets/EventRankerServlet.java
  project/src/main/webapp/event-details.js
  project/src/main/webapp/events-feed.js
  project/src/main/webapp/shared.js
Labels: API, UI

#192 Allow hosts to upload event pictures
  project/src/main/java/com/google/sps/servlets/BlobHandlerEventServlet.java
  project/src/main/java/com/google/sps/servlets/BlobHandlerUserServlet.java
  project/src/main/java/com/google/sps/servlets/BlobUrlServlet.java
  project/src/main/java/com/google/sps/utilities/CommonUtils.java
  project/src/main/java/com/google/sps/utilities/TestUtils.java
  project/src/main/webapp/event-details.html
  project/src/main/webapp/event-details.js
  project/src/main/webapp/profile-edit.js
  project/src/main/webapp/profile.js
  project/src/main/webapp/shared.js
  project/src/test/java/com/google/sps/BlobHandlerEventTest.java
  project/src/test/java/com/google/sps/BlobHandlerUserTest.java
Labels: API, DB, LIB, UI

#200 [1/X] Accessory UI changes
  project/src/main/java/com/google/sps/data/Event.java
  project/src/main/java/com/google/sps/servlets/BlobHandlerEventServlet.java
  project/src/main/webapp/create-volunteering-opportunity.css
  project/src/main/webapp/create-volunteering-opportunity.html
  project/src/main/webapp/create-volunteering-opportunity.js
  project/src/main/webapp/event-details.css
  project/src/main/webapp/event-details.html
  project/src/main/webapp/event-details.js
  project/src/main/webapp/events-feed.js
  project/src/main/webapp/header.html
  project/src/main/webapp/profile.css
  project/src/main/webapp/profile.html
  project/src/main/webapp/profile.js
  project/src/main/webapp/script.js
  project/src/main/webapp/shared.js
  project/src/main/webapp/styles.css
Labels: API, UI, bug

#201 Additional UI polish
  project/src/main/webapp/assets/lion.jpg
  project/src/main/webapp/create-event.css
  project/src/main/webapp/create-event.html
  project/src/main/webapp/event-edit.html
  project/src/main/webapp/event-edit.js
  project/src/main/webapp/header.html
  project/src/main/webapp/index.css
  project/src/main/webapp/styles.css
Labels: UI, enhancement

#223 [Ready for review] Changes from practice demo
  project/src/main/webapp/assets/lion.jpg
  project/src/main/webapp/assets/lion.png
  project/src/main/webapp/event-card.html
  project/src/main/webapp/event-details.js
  project/src/main/webapp/events-feed.css
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/events-feed.js
  project/src/main/webapp/header.html
  project/src/main/webapp/index.html
  project/src/main/webapp/profile-edit.html
  project/src/main/webapp/profile-edit.js
  project/src/main/webapp/profile.css
  project/src/main/webapp/profile.html
  project/src/main/webapp/profile.js
  project/src/main/webapp/shared.js
  project/src/main/webapp/styles.css
Labels: UI

#226 Bug fix for user profile picture persisting
  project/src/main/java/com/google/sps/servlets/UserProfileUpdateServlet.java
Labels: API, DB

#227 Change event ordering to left-right instead of top-bottom
  project/src/main/webapp/event-card.html
  project/src/main/webapp/events-feed.css
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/events-feed.js
Labels: UI

#224 [Review for review] Connect ranking and filtering (BACKEND)
  project/pom.xml
  project/src/main/java/com/google/sps/servlets/EventRankerServlet.java
  project/src/main/java/com/google/sps/utilities/EventRanker.java
  project/src/main/java/com/google/sps/utilities/GetLabelCategories.java
  project/src/test/java/com/google/sps/EventRankerServletTest.java
  project/src/test/java/com/google/sps/EventRankerTest.java
  project/src/test/java/com/google/sps/GetLabelCategoriesTest.java
Labels: API, DB

#235 Add back events with no matches at the bottom
  project/src/main/java/com/google/sps/utilities/EventRanker.java
  project/src/test/java/com/google/sps/EventRankerServletTest.java
  project/src/test/java/com/google/sps/EventRankerTest.java
Labels: API

#241 Style profile and profile-edit pages (FRONTEND)
  project/src/main/webapp/create-event.css
  project/src/main/webapp/create-event.html
  project/src/main/webapp/event-edit.html
  project/src/main/webapp/events-feed.css
  project/src/main/webapp/events-feed.html
  project/src/main/webapp/events-feed.js
  project/src/main/webapp/profile-edit.css
  project/src/main/webapp/profile-edit.html
  project/src/main/webapp/profile-edit.js
  project/src/main/webapp/profile.css
  project/src/main/webapp/profile.html
  project/src/main/webapp/profile.js
  project/src/main/webapp/shared.js
  project/src/main/webapp/styles.css
Labels: UI
